{{- $releaseName := .Release.Name -}}
{{- $chartName := include "detiler.name" . -}}
{{- if .Values.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "detiler.environment" . }}
    release: {{ $releaseName }}
    {{- include "detiler.labels" . | nindent 4 }}
type: Opaque
data:
{{- if or (ne .Values.redisConfig.username "") (ne .Values.redisConfig.password "") }}
  REDIS_USERNAME: {{ .Values.redisConfig.username | b64enc }}
  REDIS_PASSWORD: {{ .Values.redisConfig.password | b64enc }}
{{- end }}
{{- end }}
